name: Generate Snake

on:
  # Se ejecuta cada 6 horas
  schedule:
    - cron: "0 */6 * * *"
  
  # Permite ejecutarlo manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Tommyx66
          # PALETA CYBERPUNK (Cyan/PÃºrpura)
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#00f2ff&color_dots=#0d1117,#3c096c,#bd00ff,#9d4edd,#00f2ff
            dist/github-contribution-grid-snake-dark.svg?color_snake=#00f2ff&color_dots=#0d1117,#3c096c,#bd00ff,#9d4edd,#00f2ff
            
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update snake animation [skip ci]"
          # ESTO ES LA CLAVE: Firmar con TUS datos para que cuente el commit
          author: Tommyx66 <tommzx66@gmail.com>
          committer: Tommyx66 <tommzx66@gmail.com>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
